Repository harvester/harvester-installer, pull requests merged in 2025-02, with the labels that each got.

#942 fix kernel command line for management interface
  pkg/util/cmdline.go
  pkg/util/cmdline_test.go
Labels: bug

#939 Add snapshot-validation-webhook related resources to diff
  pkg/config/templates/rancherd-10-harvester.yaml
Labels: backport-to/v1.5

#949 [Backport v1.5] fix kernel command line for management interface
  pkg/util/cmdline.go
  pkg/util/cmdline_test.go
Labels: bug

#951 Fix incorrect Grafana CPU Usage panel
  pkg/config/templates/rancherd-12-monitoring-dashboard.yaml
Labels: backport-to/v1.4, backport-to/v1.5

#957 drop patching of harvester chart for arm builds
  scripts/build-bundle
  scripts/hack/patch-harvester-chart
Labels: backport-to/v1.5

#960 fix: ensure passive.img is sparse after install
  package/harvester-os/files/usr/sbin/harv-install
Labels: backport-to/v1.4, backport-to/v1.5

#968 fix: use same COS_* partition sizes regardless of seaparate data disk
  pkg/config/cos.go
  pkg/console/util.go
Labels: backport-to/v1.4, backport-to/v1.5

#938 change multipath default behaviour
  pkg/config/cos.go
  pkg/console/util.go
Labels: backport-to/v1.4, backport-to/v1.5

#984 fix: persist /etc/nvme
  pkg/config/templates/cos-rootfs.yaml
Labels: backport-to/v1.5

#980 Bump monitoring and logging
  pkg/config/templates/patch/rancher-logging/105.2.0+up4.10.0/configmap.yaml
  pkg/config/templates/patch/rancher-logging/105.2.0+up4.10.0/daemonset.yaml
  pkg/config/templates/patch/rancher-logging/105.2.0+up4.10.0/eventtailer.yaml
  pkg/config/templates/patch/rancher-logging/105.2.0+up4.10.0/fluentbitagent.yaml
  pkg/config/templates/patch/rancher-monitoring-crd/105.1.2+up61.3.2/patch-values-shell-version.diff
  pkg/config/templates/patch/rancher-monitoring/105.1.2+up61.3.2/nginx-config.yaml
  pkg/config/templates/patch/rancher-monitoring/105.1.2+up61.3.2/patch-values-shell-version.diff
  scripts/build
  scripts/build-bundle
  scripts/hack/patch-rancher-logging
  scripts/images/rancher-images.txt
  scripts/patch-monitoring-logging
  scripts/version-logging
  scripts/version-monitoring
Labels: backport-to/v1.5
